version: '3.2'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT-3005}:3005"
    depends_on:
      - mongodb
    networks:
      - backend-network
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./:/app
    
  mongodb:
    image: mongo:5.0
    container_name: mongo
    ports:
      - "${MONGODB_PORT-27017}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE}
    networks:
      - backend-network
    volumes:
      - mongodb-data:/data/db

networks:
  backend-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local